name: pinterest
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_staggered_grid_view:
  sqflite: ^1.2.0
  flutter_block: ^3.2.0
  hovering: ^1.0.4
  flutter_gifimage: ^1.0.0
  transparent_image: ^1.0.0
  http: ^0.12.2
  flutter_dotenv: 2.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
